//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class scene
{

    private sceneEvent[] eventField;

    private string nameField;

    private string nextSceneField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("event")]
    public sceneEvent[] @event
    {
        get
        {
            return this.eventField;
        }
        set
        {
            this.eventField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nextScene
    {
        get
        {
            return this.nextSceneField;
        }
        set
        {
            this.nextSceneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class sceneEvent
{

    private sceneEventDialog dialogField;

    private sceneEventResponse responseField;

    private sceneEventAnimation animationField;

    private sceneEventWait waitField;

    private sceneEventTrigger triggerField;

    private sceneEventMemory memoryField;

    private string idField;

    private string agentField;

    private string jump_idField;

    /// <remarks/>
    public sceneEventDialog dialog
    {
        get
        {
            return this.dialogField;
        }
        set
        {
            this.dialogField = value;
        }
    }

    /// <remarks/>
    public sceneEventResponse response
    {
        get
        {
            return this.responseField;
        }
        set
        {
            this.responseField = value;
        }
    }

    /// <remarks/>
    public sceneEventAnimation animation
    {
        get
        {
            return this.animationField;
        }
        set
        {
            this.animationField = value;
        }
    }

    /// <remarks/>
    public sceneEventWait wait
    {
        get
        {
            return this.waitField;
        }
        set
        {
            this.waitField = value;
        }
    }

    /// <remarks/>
    public sceneEventTrigger trigger
    {
        get
        {
            return this.triggerField;
        }
        set
        {
            this.triggerField = value;
        }
    }

    /// <remarks/>
    public sceneEventMemory memory
    {
        get
        {
            return this.memoryField;
        }
        set
        {
            this.memoryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string agent
    {
        get
        {
            return this.agentField;
        }
        set
        {
            this.agentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string jump_id
    {
        get
        {
            return this.jump_idField;
        }
        set
        {
            this.jump_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class sceneEventDialog
{

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class sceneEventResponse
{

    private sceneEventResponseGrammar[] grammarField;

    private float time_outField;

    private bool time_outFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("grammar")]
    public sceneEventResponseGrammar[] grammar
    {
        get
        {
            return this.grammarField;
        }
        set
        {
            this.grammarField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float time_out
    {
        get
        {
            return this.time_outField;
        }
        set
        {
            this.time_outField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool time_outSpecified
    {
        get
        {
            return this.time_outFieldSpecified;
        }
        set
        {
            this.time_outFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class sceneEventResponseGrammar
{

    private string[] itemField;

    private string jump_idField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item")]
    public string[] item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string jump_id
    {
        get
        {
            return this.jump_idField;
        }
        set
        {
            this.jump_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class sceneEventAnimation
{

    private float lengthField;

    private bool lengthFieldSpecified;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float length
    {
        get
        {
            return this.lengthField;
        }
        set
        {
            this.lengthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lengthSpecified
    {
        get
        {
            return this.lengthFieldSpecified;
        }
        set
        {
            this.lengthFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class sceneEventWait
{

    private float time_outField;

    private bool time_outFieldSpecified;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float time_out
    {
        get
        {
            return this.time_outField;
        }
        set
        {
            this.time_outField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool time_outSpecified
    {
        get
        {
            return this.time_outFieldSpecified;
        }
        set
        {
            this.time_outFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class sceneEventTrigger
{

    private string objectField;

    private string methodField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @object
    {
        get
        {
            return this.objectField;
        }
        set
        {
            this.objectField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string method
    {
        get
        {
            return this.methodField;
        }
        set
        {
            this.methodField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class sceneEventMemory
{

    private string rememberedField;

    private string notRemeberedField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @remembered
    {
        get
        {
            return this.rememberedField;
        }
        set
        {
            this.rememberedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string notRemembered
    {
        get
        {
            return this.notRemeberedField;
        }
        set
        {
            this.notRemeberedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}
